name: Continuous Integration

on:
  push:
    branches:
      - master
      - ci

jobs:
  "testing-suite": 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run Tests
        env: 
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        run: |
          python -m unittest discover test/automated
  deployment:
    needs: testing-suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 34.203.1.173
          username: github
          key: ${{ secrets.AMAZON_DEPLOYMENT }}
          script: |
            rm -rf spotidex
            git clone https://github.com/redbrickhut/spotidex
            python3.8 -m venv /home/github/spotidex/venv
            source /home/github/spotidex/venv/bin/activate
            cd /home/github/spotidex/
            python setup.py install